spring.datasource.url=jdbc:sqlserver://DESKTOP-DSGCHLQ:1433;instanceName=SQLEXPRESS;databaseName=reza;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=1234
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true

server.port=8081